apiVersion: v1
kind: Service
metadata:
  name: sfc-mssql
  namespace: sfc
  labels:
    app.kubernetes.io/name: sfc-mssql
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: sfc
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: kubectl
  annotations:
    owner: "krivorukandrey@gmail.com"
    purpose: "Internal ClusterIP service for MS SQL component in SFC application"
spec:
  selector:
    app.kubernetes.io/name: sfc-mssql
  type: ClusterIP
  ports:
    - name: sfc-mssql-cluster-service-port
      protocol: TCP
      port: 1433
      targetPort: 1433
  internalTrafficPolicy: Cluster