apiVersion: v1
kind: Secret
metadata:
  name: sfc-mssql-secret
  namespace: sfc
  labels:
    app.kubernetes.io/name: sfc-mssql
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: sfc
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: kubectl
  annotations:
    owner: "krivorukandrey@gmail.com"
    purpose: "Secrets for MS SQL component in SFC application"
    rotation-policy: "90-days"
immutable: true
type: Opaque
data:
  SA_PASSWORD: VGVzdDEyMzQh
  SFC_PASSWORD: VGVzdDEyMzQh