apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sfc-bff-network-policy
  namespace: sfc
  labels:
    app.kubernetes.io/name: sfc-bff
    app.kubernetes.io/component: policy
    app.kubernetes.io/part-of: sfc
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: kubectl
  annotations:
    owner: "krivorukandrey@gmail.com"
    purpose: "Network policy for Bff component in SFC application"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sfc-bff
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx          
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 7166
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-data
      ports:
        - protocol: TCP
          port: 7466
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-identity
      ports:
        - protocol: TCP
          port: 7266
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-player
      ports:
        - protocol: TCP
          port: 7366
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-team
      ports:
        - protocol: TCP
          port: 7566
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-invite
      ports:
        - protocol: TCP
          port: 7666
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-request
      ports:
        - protocol: TCP
          port: 7766
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-scheme
      ports:
        - protocol: TCP
          port: 7866
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sfc
          podSelector:
            matchLabels:
              app.kubernetes.io/name: sfc-game
      ports:
        - protocol: TCP
          port: 7966