export {
    buildPath,
    buildTitle,
    getUrlSegment,
    getUrlSegments,
    getPartUrlSegments,
    findUrlSegments,
    buildFallbackRoute,
    getRouteId,
    buildNavigationExtras,
    addNavigationExtras,
    getValueFromNavigationExtras,
    getRouteData,
    getDataFromRoute,
    getDataFromParentRoute,
    getDataFromRouteRecursively,
    buildBackNavigationExtras,
    getBackNavigationModel,
    buildActionParameters,
    getDeepestRoute,
    navigateWithOneTimeAccess,
    replaceRouteIdInPath
} from './routing.utils';