import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { RouterModule } from '@angular/router';
import { NgxSfcCommonModule } from 'ngx-sfc-common';
import { NgxSfcComponentsModule } from 'ngx-sfc-components';
import { NgxSfcInputsModule } from 'ngx-sfc-inputs';
import {
  IconTooltipComponent,
  LogoComponent,
  ThemeTogglerComponent,
  TitleComponent,
  InfoPanelComponent,
  NoDataComponent,
  BadgeComponent,
  StatsSkillsComponent,
  StatsTotalComponent,
  CarouselSliderComponent,
  AvailabilityEditComponent,
  AvailabilityFormComponent,
  AvailabilityListComponent,
  TabLabelCommonComponent,
  ShirtCarouselSliderContentComponent,
  ChangesCheckModalComponent,
  AvatarInputPlayersModalBodyComponent,
  AvatarInputPlayersModalBodyTableRowComponent,
  TeamSearchFilterGeneralComponent,
  TeamInfoComponent,
  StatusComponent,
  EnumComponent,
  BackComponent,
  TeamPreviewComponent,
  PlayerPreviewComponent,
  PanelComponent,
  CircleComponent,
  FilterTagsComponent,
  FormationCarouselSliderContentComponent,
  ExclamationModalComponent,
  SchemeInfoComponent,
  InviteTeamPlayerCancelModalComponent,
  RequestTeamPlayerAcceptModalComponent,
  RequestTeamPlayerDeclineModalComponent,
  SchemeTeamRemoveModalComponent,
  PlayerInfoComponent,
  GeneralFilterComponent,
  FootballFilterComponent,
  StatsFilterComponent,
  PlayerRowComponent,
  PlayerRowContentComponent,
  PlayerCardComponent,
  AvatarInputTeamsModalBodyComponent,
  AvatarInputTeamPlayersModalBodyComponent,
  AvatarInputTeamPlayersModalBodyTableRowComponent,
  TeamSearchFilterFinancialComponent,
  TeamSearchFilterInventaryComponent,
  TeamSearchTableRowComponent,
  TeamSearchTableCardComponent,
  TeamPlayerSearchFilterGeneralComponent,
  TeamPlayerSearchTableRowComponent,
  TeamPlayerInfoComponent,
  TeamPlayerSearchTableCardComponent,
  SchemeTeamSearchFilterGeneralComponent,
  SchemeTeamSearchFilterFormationComponent,
  SchemeTeamSearchTableRowComponent,
  SchemeTeamSearchTableCardComponent,
  StatsRadarComponent,
  StatsListComponent,
  FormProgressComponent,
  FormProgressStepComponent,
  FormProgressActionsComponent,
  GameTeamSearchFilterGeneralComponent,
  GameTeamSearchFilterFinancialComponent,
  GameTeamSearchTableRowComponent,
  GameTeamSearchFilterInventaryComponent,
  GameTeamSearchTableCardComponent,
  AvatarInputGameTeamsModalBodyComponent,
  GameTeamInfoComponent,
  InviteGamePlayerSearchFilterGeneralComponent,
  InviteGamePlayerSearchTableRowComponent,
  InviteGamePlayerSearchTableCardComponent,
  InviteGamePlayerInfoComponent,
  InviteGamePlayerCancelModalComponent,
  InviteGameTeamInfoComponent,
  InviteGameTeamSearchTableCardComponent,
  InviteGameTeamSearchTableRowComponent,
  InviteGameTeamSearchFilterGeneralComponent,
  InviteGameTeamCancelModalComponent,
  RequestGamePlayerAcceptModalComponent,
  RequestGamePlayerDeclineModalComponent,
  RequestGameTeamDeclineModalComponent,
  RequestGameTeamAcceptModalComponent,
  RequestGamePlayerInfoComponent,
  RequestGameTeamInfoComponent,
  RequestGamePlayerSearchTableCardComponent,
  RequestGamePlayerSearchTableRowComponent,
  RequestGamePlayerSearchFilterGeneralComponent,
  RequestGameTeamSearchTableCardComponent,
  RequestGameTeamSearchFilterGeneralComponent,
  RequestGameTeamSearchTableRowComponent,
  GamePlayerInfoComponent,
  GamePlayerSearchTableCardComponent,
  GamePlayerSearchTableRowComponent,
  GamePlayerSearchFilterGeneralComponent,
  LinkComponent,
  GameTeamPlayerInfoComponent,
  GameTeamPlayerSearchFilterGeneralComponent,
  GameTeamPlayerSearchTableRowComponent,
  GameTeamPlayerSearchTableCardComponent,
  SchemeGameTeamSearchFilterGeneralComponent,
  SchemeGameTeamSearchFilterFormationComponent,
  SchemeGameTeamSearchTableRowComponent,
  SchemeGameTeamSearchTableCardComponent,
  SchemeGameTeamInfoComponent,
  SchemeGameTeamModalRemoveComponent
} from './components';
import { TimePipe, DayPipe } from './pipes';

@NgModule({
  declarations: [
    LogoComponent,
    ThemeTogglerComponent,
    IconTooltipComponent,
    TitleComponent,
    InfoPanelComponent,
    NoDataComponent,
    BadgeComponent,
    ChangesCheckModalComponent,
    ExclamationModalComponent,
    StatusComponent,
    EnumComponent,
    BackComponent,
    LinkComponent,
    PanelComponent,
    CircleComponent,
    FilterTagsComponent,
    // form progress
    FormProgressComponent,
    FormProgressStepComponent,
    FormProgressActionsComponent,
    // stats
    StatsSkillsComponent,
    StatsTotalComponent,
    StatsRadarComponent,
    StatsListComponent,
    // availability
    AvailabilityEditComponent,
    AvailabilityFormComponent,
    AvailabilityListComponent,
    // extends
    ShirtCarouselSliderContentComponent,
    FormationCarouselSliderContentComponent,
    CarouselSliderComponent,
    TabLabelCommonComponent,
    AvatarInputPlayersModalBodyComponent,
    AvatarInputPlayersModalBodyTableRowComponent,
    AvatarInputTeamsModalBodyComponent,
    AvatarInputTeamPlayersModalBodyComponent,
    AvatarInputTeamPlayersModalBodyTableRowComponent,
    AvatarInputGameTeamsModalBodyComponent,
    // feature/player
    PlayerInfoComponent,
    PlayerPreviewComponent,
    GeneralFilterComponent,
    FootballFilterComponent,
    StatsFilterComponent,
    PlayerRowComponent,
    PlayerRowContentComponent,
    PlayerCardComponent,
    // feature/team
    TeamSearchFilterGeneralComponent,
    TeamSearchFilterFinancialComponent,
    TeamSearchFilterInventaryComponent,
    TeamSearchTableRowComponent,
    TeamSearchTableCardComponent,
    TeamInfoComponent,
    TeamPreviewComponent,
    // feature/team/player
    TeamPlayerSearchFilterGeneralComponent,
    TeamPlayerSearchTableRowComponent,
    TeamPlayerSearchTableCardComponent,
    TeamPlayerInfoComponent,
    // feature/scheme
    SchemeInfoComponent,
    // feature/scheme/team
    SchemeTeamRemoveModalComponent,
    SchemeTeamSearchFilterGeneralComponent,
    SchemeTeamSearchFilterFormationComponent,
    SchemeTeamSearchTableRowComponent,
    SchemeTeamSearchTableCardComponent,
    // feature/scheme/game/team
    SchemeGameTeamInfoComponent,
    SchemeGameTeamSearchFilterGeneralComponent,
    SchemeGameTeamSearchFilterFormationComponent,
    SchemeGameTeamSearchTableRowComponent,
    SchemeGameTeamSearchTableCardComponent,
    SchemeGameTeamModalRemoveComponent,
    // feature/invite
    InviteTeamPlayerCancelModalComponent,
    // feature/invite/game/player
    InviteGamePlayerInfoComponent,
    InviteGamePlayerCancelModalComponent,
    InviteGamePlayerSearchFilterGeneralComponent,
    InviteGamePlayerSearchTableRowComponent,
    InviteGamePlayerSearchTableCardComponent,
    // feature/invite/game/team
    InviteGameTeamInfoComponent,
    InviteGameTeamCancelModalComponent,
    InviteGameTeamSearchFilterGeneralComponent,
    InviteGameTeamSearchTableRowComponent,
    InviteGameTeamSearchTableCardComponent,
    // feature/request/team/player
    RequestTeamPlayerAcceptModalComponent,
    RequestTeamPlayerDeclineModalComponent,
    // feature/request/game/player
    RequestGamePlayerInfoComponent,
    RequestGamePlayerAcceptModalComponent,
    RequestGamePlayerDeclineModalComponent,
    RequestGamePlayerSearchFilterGeneralComponent,
    RequestGamePlayerSearchTableRowComponent,
    RequestGamePlayerSearchTableCardComponent,
    // feature/request/game/team
    RequestGameTeamInfoComponent,
    RequestGameTeamAcceptModalComponent,
    RequestGameTeamDeclineModalComponent,
    RequestGameTeamSearchFilterGeneralComponent,
    RequestGameTeamSearchTableRowComponent,
    RequestGameTeamSearchTableCardComponent,
    // feature/game/team
    GameTeamSearchFilterGeneralComponent,
    GameTeamSearchFilterFinancialComponent,
    GameTeamSearchFilterInventaryComponent,
    GameTeamSearchTableRowComponent,
    GameTeamSearchTableCardComponent,
    GameTeamInfoComponent,
    // feature/game/team/player
    GameTeamPlayerInfoComponent,
    GameTeamPlayerSearchFilterGeneralComponent,
    GameTeamPlayerSearchTableRowComponent,
    GameTeamPlayerSearchTableCardComponent,
    // feature/game/player
    GamePlayerInfoComponent,
    GamePlayerSearchFilterGeneralComponent,
    GamePlayerSearchTableRowComponent,
    GamePlayerSearchTableCardComponent,
    // pipes
    TimePipe,
    DayPipe
  ],
  imports: [
    CommonModule,
    RouterModule,
    ReactiveFormsModule,
    HttpClientModule,
    FontAwesomeModule,
    NgxSfcCommonModule,
    NgxSfcComponentsModule,
    NgxSfcInputsModule
  ],
  exports: [
    LogoComponent,
    ThemeTogglerComponent,
    IconTooltipComponent,
    TitleComponent,
    InfoPanelComponent,
    StatusComponent,
    EnumComponent,
    BackComponent,
    LinkComponent,
    PanelComponent,
    CircleComponent,
    NoDataComponent,
    BadgeComponent,
    ChangesCheckModalComponent,
    ExclamationModalComponent,
    FilterTagsComponent,
    // form progress
    FormProgressComponent,
    FormProgressActionsComponent,
    // stats
    StatsSkillsComponent,
    StatsTotalComponent,
    StatsRadarComponent,
    StatsListComponent,
    // availability
    AvailabilityEditComponent,
    AvailabilityFormComponent,
    AvailabilityListComponent,
    // extends
    CarouselSliderComponent,
    ShirtCarouselSliderContentComponent,
    FormationCarouselSliderContentComponent,
    TabLabelCommonComponent,
    AvatarInputPlayersModalBodyComponent,
    AvatarInputTeamsModalBodyComponent,
    AvatarInputTeamPlayersModalBodyComponent,
    AvatarInputGameTeamsModalBodyComponent,
    // feature/player
    PlayerInfoComponent,
    PlayerPreviewComponent,
    GeneralFilterComponent,
    FootballFilterComponent,
    StatsFilterComponent,
    PlayerRowComponent,
    PlayerRowContentComponent,
    PlayerCardComponent,
    // feature/team
    TeamSearchFilterGeneralComponent,
    TeamSearchFilterFinancialComponent,
    TeamSearchFilterInventaryComponent,
    TeamSearchTableRowComponent,
    TeamSearchTableCardComponent,
    TeamInfoComponent,
    TeamPreviewComponent,
    // feature/team/player
    TeamPlayerSearchFilterGeneralComponent,
    TeamPlayerSearchTableRowComponent,
    TeamPlayerSearchTableCardComponent,
    TeamPlayerInfoComponent,
    // feature/scheme
    SchemeInfoComponent,
    // feature/scheme/team
    SchemeTeamRemoveModalComponent,
    SchemeTeamSearchFilterGeneralComponent,
    SchemeTeamSearchFilterFormationComponent,
    SchemeTeamSearchTableRowComponent,
    SchemeTeamSearchTableCardComponent,
    // feature/scheme/game/team
    SchemeGameTeamInfoComponent,
    SchemeGameTeamSearchFilterGeneralComponent,
    SchemeGameTeamSearchFilterFormationComponent,
    SchemeGameTeamSearchTableRowComponent,
    SchemeGameTeamSearchTableCardComponent,
    SchemeGameTeamModalRemoveComponent,
    // feature/invite
    InviteTeamPlayerCancelModalComponent,
    // feature/invite/game/player
    InviteGamePlayerInfoComponent,
    InviteGamePlayerCancelModalComponent,
    InviteGamePlayerSearchFilterGeneralComponent,
    InviteGamePlayerSearchTableRowComponent,
    InviteGamePlayerSearchTableCardComponent,
    // feature/invite/game/team
    InviteGameTeamInfoComponent,
    InviteGameTeamCancelModalComponent,
    InviteGameTeamSearchFilterGeneralComponent,
    InviteGameTeamSearchTableRowComponent,
    InviteGameTeamSearchTableCardComponent,
    // feature/request/team/player
    RequestTeamPlayerAcceptModalComponent,
    RequestTeamPlayerDeclineModalComponent,
    // feature/request/game/player
    RequestGamePlayerInfoComponent,
    RequestGamePlayerAcceptModalComponent,
    RequestGamePlayerDeclineModalComponent,
    RequestGamePlayerSearchFilterGeneralComponent,
    RequestGamePlayerSearchTableRowComponent,
    RequestGamePlayerSearchTableCardComponent,
    // feature/request/game/team
    RequestGameTeamInfoComponent,
    RequestGameTeamAcceptModalComponent,
    RequestGameTeamDeclineModalComponent,
    RequestGameTeamSearchFilterGeneralComponent,
    RequestGameTeamSearchTableRowComponent,
    RequestGameTeamSearchTableCardComponent,
    // feature/game/team
    GameTeamSearchFilterGeneralComponent,
    GameTeamSearchFilterFinancialComponent,
    GameTeamSearchFilterInventaryComponent,
    GameTeamSearchTableRowComponent,
    GameTeamSearchTableCardComponent,
    GameTeamInfoComponent,
    // feature/game/team/player
    GameTeamPlayerInfoComponent,
    GameTeamPlayerSearchFilterGeneralComponent,
    GameTeamPlayerSearchTableRowComponent,
    GameTeamPlayerSearchTableCardComponent,
    // feature/game/player
    GamePlayerInfoComponent,
    GamePlayerSearchFilterGeneralComponent,
    GamePlayerSearchTableRowComponent,
    GamePlayerSearchTableCardComponent,
    // pipes
    TimePipe,
    DayPipe
  ]
})
export class ShareModule { } 