apiVersion: v1
kind: Secret
metadata:
  name: sfc-redis-secret
  namespace: sfc
  labels:
    app.kubernetes.io/name: sfc-redis
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: sfc
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: kubectl
  annotations:
    owner: "krivorukandrey@gmail.com"
    purpose: "Secrets for Redis component in SFC application"
    rotation-policy: "90-days"
immutable: true
type: Opaque
stringData:
  users.acl: |
    user sfc on >Test1234! +@all ~*
    user default off
  username: sfc
  password: Test1234!
