apiVersion: v1
kind: Namespace
metadata:
  name: sfc
  labels:
    app.kubernetes.io/name: sfc
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: sfc
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: kubectl
  annotations:
    owner: "krivorukandrey@gmail.com"
    purpose: "Namespace for SFC application"