server {
    listen 80;
    listen [::]:80;

    server_name
        sfc-data
        sfc-identity
        sfc-player
        sfc-team
        sfc-invite
        sfc-request
        sfc-scheme
        sfc-bff
    ;

    return 301 https://$host$request_uri;
}