server {
    listen 443 ssl http2;
    server_name sfc-scheme;

    ssl_certificate     /etc/nginx/ssl/sfc-scheme/sfc-scheme.crt;
    ssl_certificate_key /etc/nginx/ssl/sfc-scheme/sfc-scheme.key;

    include /etc/nginx/conf.d/_proxy-common.conf;

    location / {
        proxy_pass https://sfc_scheme_up;
        # proxy_ssl_name sfc-scheme.internal.example;
    }
}