server {
    listen 443 ssl http2;
    server_name sfc-request;

    ssl_certificate     /etc/nginx/ssl/sfc-request/sfc-request.crt;
    ssl_certificate_key /etc/nginx/ssl/sfc-request/sfc-request.key;

    include /etc/nginx/conf.d/_proxy-common.conf;

    location / {
        proxy_pass https://sfc_request_up;
        # proxy_ssl_name sfc-request.internal.example;
    }
}