server {
    listen 443 ssl http2;
    server_name sfc-identity;

    ssl_certificate     /etc/nginx/ssl/sfc-identity/sfc-identity.crt;
    ssl_certificate_key /etc/nginx/ssl/sfc-identity/sfc-identity.key;

    include /etc/nginx/conf.d/_proxy-common.conf;

    location / {
        proxy_pass https://sfc_identity_up;
        # proxy_ssl_name sfc-identity.internal.example;
    }
}