server {
    listen 443 ssl http2;
    server_name sfc-team;

    ssl_certificate     /etc/nginx/ssl/sfc-team/sfc-team.crt;
    ssl_certificate_key /etc/nginx/ssl/sfc-team/sfc-team.key;

    include /etc/nginx/conf.d/_proxy-common.conf;

    location / {
        proxy_pass https://sfc_team_up;
        # proxy_ssl_name sfc-team.internal.example;
    }
}