server {
    listen 443 ssl http2;
    server_name sfc-invite;

    ssl_certificate     /etc/nginx/ssl/sfc-invite/sfc-invite.crt;
    ssl_certificate_key /etc/nginx/ssl/sfc-invite/sfc-invite.key;

    include /etc/nginx/conf.d/_proxy-common.conf;

    location / {
        proxy_pass https://sfc_invite_up;
        # proxy_ssl_name sfc-invite.internal.example;
    }
}