server {
    listen 443 ssl http2;
    server_name sfc-player;

    ssl_certificate     /etc/nginx/ssl/sfc-player/sfc-player.crt;
    ssl_certificate_key /etc/nginx/ssl/sfc-player/sfc-player.key;

    include /etc/nginx/conf.d/_proxy-common.conf;

    location / {
        proxy_pass https://sfc_player_up;
        # proxy_ssl_name sfc-player.internal.example;
    }
}