
# Upstream services (Kestrel behind TLS on varied ports)
upstream sfc_data_up     { server sfc-data:7466;    }
upstream sfc_identity_up { server sfc-identity:7266; }
upstream sfc_player_up   { server sfc-player:7366;   }
upstream sfc_team_up     { server sfc-team:7566;    }
upstream sfc_invite_up   { server sfc-invite:7666;   }
upstream sfc_request_up  { server sfc-request:7766;  }
upstream sfc_scheme_up   { server sfc-scheme:7866;  }
upstream sfc_bff_up      { server sfc-bff:7166;    }