export { SearchPageComponent } from "./search.page.component";
export { GeneralFilterComponent } from "./parts/filters/general/general-filter.component";
export { FootballFilterComponent } from "./parts/filters/football/football-filter.component";
export { StatsFilterComponent } from "./parts/filters/stats/stats-filter.component";
export { PlayersRecommendationComponent } from "./parts/recomendation/players-recommendation.component";
export { PlayerRecommendationComponent } from "./parts/recomendation/parts/player/player-recommendation.component";
export { PlayerRowComponent } from "./parts/table/row/player-row.component";
export { PlayerRowContentComponent } from "./parts/table/row-content/player-row-content.component";
export { PlayerCardComponent } from "./parts/table/card/player-card.component";