#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Ready to commit changes!'

echo 'Format dotnet'

dotnet husky run --name dotnet-format-staged-files

echo 'Build dotnet'

dotnet husky run --name dotnet-build

echo 'Lint npm'

dotnet husky run --name npm-lint

echo 'Build npm'

dotnet husky run --name npm-build

echo 'Completed pre-commit changes'