#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Ready to push changes!'

echo 'Running dotnet unit tests...'

dotnet husky run --name dotnet-test

echo 'Generate dotnet unit tests report...'

dotnet husky run --name reportgenerator-create

echo 'Running npm unit tests & code coverage...'

dotnet husky run --npm-test

echo 'Completed pre-push changes'