#github action to build and test SFC.Bff application

name: Build and Test SFC.Bff Application

on:
  workflow_dispatch:  
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: 8.0.x 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Dotnet restore dependencies
        run: dotnet restore

      - name: Dotnet build
        run: dotnet build --no-restore --configuration Release

      - name: Dotnet test
        run: dotnet test --no-restore --no-build --configuration Release --verbosity normal /p:CollectCoverage=true /p:Threshold=0 /p:ThresholdStat=total

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Install dependencies
        run: npm ci # Use npm ci for clean installs in CI/CD environments

      - name: Npm build
        run: npm run build

      - name: Npm test
        run: npm run test:code-coverage